Repository AY2021S1-CS2113T-F12-2/tp, pull requests merged in 2020-10, with the labels that each got.

#42 UserProfile updates and JUnit tests for Human subclasses
  src/main/java/seedu/duke/Character.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Gender.java
  src/main/java/seedu/duke/Human.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/UserProfile.java
  src/main/java/seedu/duke/VoiceActor.java
  src/test/java/seedu/duke/CharacterTest.java
  src/test/java/seedu/duke/UserProfileTest.java
  src/test/java/seedu/duke/VoiceActorTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#51 Merge Add Anime to Watchlist
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/Watchlist.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Enhancement, type.Task

#52 Merge ChanJianHao-Honorifics
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/UserProfile.java
Labels: priority.Medium, type.Enhancement

#53 Merge ChanJianHao-Exception-Update
  src/main/java/seedu/duke/AniException.java
  src/main/java/seedu/duke/Character.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/DukeException.java
  src/main/java/seedu/duke/Human.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UserProfile.java
  src/main/java/seedu/duke/VoiceActor.java
  src/test/java/seedu/duke/CharacterTest.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/UserProfileTest.java
  src/test/java/seedu/duke/VoiceActorTest.java
Labels: priority.Medium, type.Enhancement

#64 Merge MichaelDinata-ParserCommand
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddProfileCommand.java
  src/main/java/seedu/duke/command/AddToWatchlistCommand.java
  src/main/java/seedu/duke/command/BookmarkAnimeCommand.java
  src/main/java/seedu/duke/command/BrowseAnimeCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CreateWatchlistCommand.java
  src/main/java/seedu/duke/command/EditProfileCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.High, type.Task

#74 Merge ChanJianHao-User-Update
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddProfileCommand.java
  src/main/java/seedu/duke/command/AddToWatchlistCommand.java
  src/main/java/seedu/duke/command/AddUserCommand.java
  src/main/java/seedu/duke/command/BookmarkAnimeCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CreateWatchlistCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/WatchlistCommand.java
  src/main/java/seedu/duke/human/User.java
  src/main/java/seedu/duke/human/UserManagement.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/human/UserManagementTest.java
  src/test/java/seedu/duke/human/UserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#89 Assertion and logging for Parser and addToWatchlist
  src/main/java/seedu/duke/command/AddToWatchlistCommand.java
  src/main/java/seedu/duke/command/BrowseCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/watchlist/Watchlist.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#101 Fix UserManagement.java for setActiveUser()
  src/main/java/seedu/duke/human/UserManagement.java
  src/test/java/seedu/duke/command/WatchlistCommandTest.java
Labels: severity.High

#102 Merge ChanJianHao-User-Management-Updates
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddUserCommand.java
  src/main/java/seedu/duke/human/User.java
  src/main/java/seedu/duke/human/UserManagement.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/human/UserManagementTest.java
  src/test/java/seedu/duke/storage/DecoderTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Enhancement

#110 Minor changes for loggers and implemented help method
  src/main/java/seedu/duke/command/AddToWatchlistCommand.java
  src/main/java/seedu/duke/command/BookmarkAnimeCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/SwitchUserCommand.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.High, type.Task

#113 Merge ChanJianHao-Workspace-Update
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddToWatchlistCommand.java
  src/main/java/seedu/duke/command/AddUserCommand.java
  src/main/java/seedu/duke/command/AddWorkspaceCommand.java
  src/main/java/seedu/duke/command/BookmarkAnimeCommand.java
  src/main/java/seedu/duke/command/BrowseCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/SwitchWorkspaceCommand.java
  src/main/java/seedu/duke/command/WatchlistCommand.java
  src/main/java/seedu/duke/human/User.java
  src/main/java/seedu/duke/human/UserManagement.java
  src/main/java/seedu/duke/human/Workspace.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/Decoder.java
  src/main/java/seedu/duke/storage/Encoder.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/BrowseCommandTest.java
  src/test/java/seedu/duke/command/WatchlistCommandTest.java
  src/test/java/seedu/duke/human/UserManagementTest.java
  src/test/java/seedu/duke/human/UserTest.java
  src/test/java/seedu/duke/human/WorkspaceTest.java
  src/test/java/seedu/duke/storage/DecoderTest.java
  src/test/java/seedu/duke/storage/EncoderTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Task

#136 Add to watchlist and remove anime from watchlist
  src/main/java/seedu/duke/command/AddToWatchlistCommand.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/parser/AddToWatchlistParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/RemoveCommandParser.java
  src/main/java/seedu/duke/storage/WatchlistStorage.java
  src/main/java/seedu/duke/watchlist/Watchlist.java
  src/test/data/Default/watchlist.txt
  src/test/java/seedu/duke/command/AddToWatchlistCommandTest.java
  src/test/java/seedu/duke/command/RemoveCommandTest.java
  src/test/java/seedu/duke/command/WatchlistCommandTest.java
  src/test/java/seedu/duke/parser/AddToWatchlistParserTest.java
  src/test/java/seedu/duke/parser/RemoveCommandParserTest.java
  src/test/java/seedu/duke/watchlist/WatchlistTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Enhancement, type.Task

#141 Merge ChanJianHao-Logger
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/anime/AnimeStorage.java
  src/main/java/seedu/duke/command/AddToWatchlistCommand.java
  src/main/java/seedu/duke/command/BookmarkAnimeCommand.java
  src/main/java/seedu/duke/command/BrowseCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/InfoCommand.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/SwitchWorkspaceCommand.java
  src/main/java/seedu/duke/human/User.java
  src/main/java/seedu/duke/logger/AniLogger.java
  src/main/java/seedu/duke/parser/AddToWatchlistParser.java
  src/main/java/seedu/duke/parser/BookmarkParser.java
  src/main/java/seedu/duke/parser/BrowseParser.java
  src/main/java/seedu/duke/parser/InfoParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/RemoveCommandParser.java
  src/main/java/seedu/duke/parser/WatchlistParser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Epic

#150 Merge ChanJianHao-Add-Tests
  src/main/java/seedu/duke/command/AddWorkspaceCommand.java
  src/main/java/seedu/duke/human/Character.java
  src/main/java/seedu/duke/human/Human.java
  src/main/java/seedu/duke/human/User.java
  src/main/java/seedu/duke/human/VoiceActor.java
  src/main/java/seedu/duke/human/Workspace.java
  src/main/java/seedu/duke/parser/AddWorkspaceParser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/AddWorkspaceCommandTest.java
  src/test/java/seedu/duke/human/UserTest.java
  src/test/java/seedu/duke/human/WorkspaceTest.java
  src/test/java/seedu/duke/parser/AddWorkspaceParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Enhancement

#162 Merge ChanJianHao-UGDG-2101-Updates
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AniChan-Logo.png
  docs/images/User-Class-Diagram.png
Labels: priority.Medium

#185 Merge ChanJianHao-UG-Workspace
  docs/UserGuide.md
  src/main/java/anichan/command/WorkspaceCommand.java
  src/test/java/anichan/command/WorkspaceCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#189 Merge MichaelDinata-JUnitTests and Update UserGuide
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/User-Class-Diagram.PNG
  docs/team/michaeldinata.md
  src/main/java/anichan/command/AddToWatchlistCommand.java
  src/main/java/anichan/command/BookmarkCommand.java
  src/main/java/anichan/command/BrowseCommand.java
  src/main/java/anichan/command/HelpCommand.java
  src/main/java/anichan/command/RemoveCommand.java
  src/main/java/anichan/command/SearchCommand.java
  src/main/java/anichan/command/ViewWatchlistCommand.java
  src/main/java/anichan/parser/AddToWatchlistParser.java
  src/main/java/anichan/parser/BookmarkParser.java
  src/main/java/anichan/parser/BrowseParser.java
  src/main/java/anichan/parser/InfoParser.java
  src/main/java/anichan/parser/Parser.java
  src/main/java/anichan/parser/RemoveCommandParser.java
  src/main/java/anichan/parser/ViewWatchlistParser.java
  src/test/java/anichan/command/InfoCommandTest.java
  src/test/java/anichan/command/RemoveCommandTest.java
  src/test/java/anichan/command/ViewWatchlistCommandTest.java
  src/test/java/anichan/parser/AddToWatchlistParserTest.java
  src/test/java/anichan/parser/InfoParserTest.java
  src/test/java/anichan/parser/RemoveCommandParserTest.java
  src/test/java/anichan/parser/ViewWatchlistParserTest.java
Labels: priority.High, type.Task

#195 Merge ChanJianHao-V2-UGDG-Updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ChanJianHao.md
  src/main/java/anichan/human/User.java
  src/main/java/anichan/human/Workspace.java
  src/main/java/anichan/logger/AniLogger.java
  src/main/java/anichan/storage/StorageManager.java
  src/test/java/anichan/commands/WorkspaceCommandTest.java
  src/test/java/anichan/human/UserTest.java
  src/test/java/anichan/parser/WorkspaceParserTest.java
  src/test/java/anichan/storage/StorageManagerTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Task

#200 Bug fix for remove command
  src/main/java/anichan/commands/RemoveCommand.java
Labels: type.Bug, type.Task

#202 Merge MichaelDinata-DeveloperGuide
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#206 Merge ChanJianHao-V2-DG-Workspace-Updates
  docs/DeveloperGuide.md
  docs/images/WorkspaceCommand-After-Create.png
  docs/images/WorkspaceCommand-After-Delete.png
  docs/images/WorkspaceCommand-After-Switch.png
  docs/images/WorkspaceCommand-Initial-State.png
  docs/images/WorkspaceCommand-Sequence-Diagram.png
  src/main/java/anichan/commands/WorkspaceCommand.java
  src/main/java/anichan/parser/WorkspaceParser.java
  src/main/java/anichan/storage/StorageManager.java
  src/test/java/anichan/parser/WorkspaceParserTest.java
Labels: priority.Medium, type.Task

#209 Merge MichaelDinata-DeveloperGuide
  docs/DeveloperGuide.md
  docs/images/AddToWatchlist-Step1-3-Sequence-Diagram.png
  docs/images/AddToWatchlist-Step4-6-Sequence-Diagram.png
  docs/images/InfoCommand-Step1-3-Sequence-Diagram.png
  docs/images/InfoCommand-Step4-6-Sequence-Diagram.png
  docs/images/ViewWatchlist-Step1-4-Sequence-Diagram.png
  docs/images/ViewWatchlist-Step5-7-Sequence-Diagram.png
Labels: priority.High, type.Task

#210 Merge EyoWeiChin-Javadocs
  docs/DeveloperGuide.md
  src/main/java/anichan/anime/Anime.java
  src/main/java/anichan/anime/AnimeStorage.java
  src/main/java/anichan/commands/BrowseCommand.java
  src/main/java/anichan/commands/SearchCommand.java
  src/main/java/anichan/parser/BrowseParser.java
  src/main/java/anichan/parser/CommandParser.java
  src/main/java/anichan/parser/SearchParser.java
  src/test/java/anichan/anime/AnimeTest.java
  src/test/java/anichan/commands/InfoCommandTest.java
  src/test/java/anichan/parser/SearchParserTest.java
Labels: priority.Medium, type.Enhancement

#211 Merge MichaelDinata-JavaDocs
  src/main/java/anichan/commands/AddToWatchlistCommand.java
  src/main/java/anichan/commands/ExitCommand.java
  src/main/java/anichan/commands/HelpCommand.java
  src/main/java/anichan/commands/InfoCommand.java
  src/main/java/anichan/commands/RemoveCommand.java
  src/main/java/anichan/commands/ViewWatchlistCommand.java
  src/main/java/anichan/parser/AddToWatchlistParser.java
  src/main/java/anichan/parser/InfoParser.java
  src/main/java/anichan/parser/RemoveCommandParser.java
  src/main/java/anichan/parser/ViewWatchlistParser.java
  src/main/java/anichan/watchlist/Watchlist.java
  src/test/java/anichan/commands/AddToWatchlistCommandTest.java
  src/test/java/anichan/commands/InfoCommandTest.java
  src/test/java/anichan/commands/RemoveCommandTest.java
  src/test/java/anichan/commands/ViewWatchlistCommandTest.java
  src/test/java/anichan/parser/AddToWatchlistParserTest.java
  src/test/java/anichan/parser/InfoParserTest.java
  src/test/java/anichan/parser/RemoveCommandParserTest.java
  src/test/java/anichan/parser/ViewWatchlistParserTest.java
Labels: priority.High, type.Task

#223 Bug Fixes on Parsers
  src/main/java/anichan/commands/HelpCommand.java
  src/main/java/anichan/parser/AddToWatchlistParser.java
  src/main/java/anichan/parser/InfoParser.java
  src/main/java/anichan/parser/RemoveCommandParser.java
  src/main/java/anichan/parser/ViewWatchlistParser.java
  src/main/java/anichan/watchlist/Watchlist.java
Labels: priority.High

#221 Merge ChanJianHao-V2-Tests-Updates
  docs/DeveloperGuide.md
  src/main/java/anichan/commands/Command.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Enhancement

#224 Merge MichaelDinata-BugFix
  src/main/java/anichan/parser/AddToWatchlistParser.java
  src/main/java/anichan/parser/InfoParser.java
  src/main/java/anichan/parser/RemoveCommandParser.java
  src/main/java/anichan/parser/ViewWatchlistParser.java
Labels: priority.High

#254 Merge ChanJianHao-V21-MinorFixes
  docs/Badges.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/WorkspaceCommand-Sequence-Diagram.png
  src/main/java/anichan/commands/WorkspaceCommand.java
  src/main/java/anichan/human/User.java
  src/main/java/anichan/parser/WorkspaceParser.java
  src/test/java/anichan/human/UserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#256 Merge ChanJianHao-V21-FutureImplementation
  docs/DeveloperGuide.md
  src/main/java/anichan/Main.java
  src/main/java/anichan/human/User.java
  src/test/java/anichan/MainTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Enhancement

#258 Bug fix on Estimate and some refactoring
  docs/UserGuide.md
  docs/images/Estimate-Folder-Structure-Diagram.png
  src/main/java/anichan/Main.java
  src/main/java/anichan/commands/WatchlistCommand.java
  src/main/java/anichan/parser/AddToWatchlistParser.java
  src/main/java/anichan/parser/BookmarkParser.java
  src/main/java/anichan/parser/BrowseParser.java
  src/main/java/anichan/parser/CommandParser.java
  src/main/java/anichan/parser/EstimateParser.java
  src/main/java/anichan/parser/InfoParser.java
  src/main/java/anichan/parser/RemoveCommandParser.java
  src/main/java/anichan/parser/ViewWatchlistParser.java
  src/main/java/anichan/parser/WatchlistParser.java
  src/main/java/anichan/storage/Storage.java
  src/main/java/anichan/storage/UserStorage.java
  src/main/java/anichan/storage/WatchlistStorage.java
  src/test/java/anichan/parser/EstimateParserTest.java
  src/test/java/anichan/parser/WatchlistParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.Low, type.Bug, type.Enhancement
