Repository AY2021S1-CS2113T-F12-2/tp, pull requests merged in 2020-11, with the labels that each got.

#260 Merge MichaelDinata-BugFix
  src/main/java/anichan/commands/ViewWatchlistCommand.java
  src/main/java/anichan/parser/AddToWatchlistParser.java
  src/main/java/anichan/parser/CommandParser.java
  src/main/java/anichan/parser/ExitParser.java
  src/main/java/anichan/parser/HelpParser.java
  src/main/java/anichan/parser/InfoParser.java
  src/main/java/anichan/parser/Parser.java
  src/main/java/anichan/parser/RemoveCommandParser.java
  src/main/java/anichan/parser/ViewWatchlistParser.java
Labels: priority.High, type.Bug, type.Task

#266 Merge ChanJianHao-V21-CodeQualityFixes
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/images/User-Class-Diagram.png
  docs/team/ChanJianHao.md
  src/main/java/anichan/Main.java
  src/main/java/anichan/human/Human.java
  src/main/java/anichan/human/User.java
  src/main/java/anichan/human/Workspace.java
  src/main/java/anichan/parser/CommandParser.java
  src/main/java/anichan/parser/Parser.java
  src/main/java/anichan/parser/WatchlistParser.java
  src/main/java/anichan/parser/WorkspaceParser.java
  src/test/java/anichan/human/UserTest.java
  src/test/java/anichan/parser/WorkspaceParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Enhancement, type.Task

#265 Merge MichaelDinata-JUnitTests
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/anichan/commands/ViewWatchlistCommand.java
  src/main/java/anichan/parser/AddToWatchlistParser.java
  src/main/java/anichan/parser/CommandParser.java
  src/main/java/anichan/parser/InfoParser.java
  src/main/java/anichan/parser/Parser.java
  src/main/java/anichan/parser/RemoveCommandParser.java
  src/main/java/anichan/parser/ViewWatchlistParser.java
  src/test/data/AddRemoveAnimeTest/watchlist.txt
  src/test/java/anichan/commands/AddToWatchlistCommandTest.java
  src/test/java/anichan/commands/InfoCommandTest.java
  src/test/java/anichan/commands/RemoveCommandTest.java
  src/test/java/anichan/commands/ViewWatchlistCommandTest.java
  src/test/java/anichan/parser/AddToWatchlistParserTest.java
  src/test/java/anichan/parser/InfoParserTest.java
  src/test/java/anichan/parser/RemoveCommandParserTest.java
  src/test/java/anichan/parser/ViewWatchlistParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Bug, type.Task

#269 Merge MichaelDinata-BugFix
  docs/DeveloperGuide.md
  src/main/java/anichan/commands/AddToWatchlistCommand.java
  src/main/java/anichan/commands/InfoCommand.java
  src/main/java/anichan/commands/RemoveCommand.java
  src/main/java/anichan/commands/ViewWatchlistCommand.java
  src/main/java/anichan/parser/AddToWatchlistParser.java
  src/main/java/anichan/parser/CommandParser.java
  src/main/java/anichan/parser/InfoParser.java
  src/main/java/anichan/parser/RemoveCommandParser.java
  src/main/java/anichan/parser/ViewWatchlistParser.java
  src/test/java/anichan/commands/ViewWatchlistCommandTest.java
Labels: priority.Medium, type.Task

#270 Merge MichaelDinata-Help
  docs/UserGuide.md
  src/main/java/anichan/commands/HelpCommand.java
  src/main/java/anichan/parser/HelpParser.java
Labels: priority.Medium, type.Enhancement, type.Task

#273 Merge MichaelDinata-Help
  src/main/java/anichan/commands/HelpCommand.java
Labels: priority.Medium, type.Enhancement, type.Task

#279 Merge ChanJianHao-V21-PPP
  docs/DeveloperGuide.md
  docs/team/ChanJianHao.md
  docs/team/chanjianhao.md
Labels: priority.High, type.Task

#280 Merge MichaelDinata-DeveloperGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement

#284 Update PPP and Developer Guide
  docs/DeveloperGuide.md
  docs/team/chanjianhao.md
  docs/team/michaeldinata.md
  docs/team/ongdezhi.md
  docs/team/xinbin.md
Labels: type.Documentation

#286 Merge EyoWeiChin's PPP Update
  docs/DeveloperGuide.md
  docs/team/eyoweichin.md
  docs/team/ongdezhi.md
  docs/team/xinbin.md
Labels: type.Documentation

#285 Merge ChanJianHao-V21-ManualTesting-Docs
  docs/DeveloperGuide.md
  docs/team/chanjianhao.md
Labels: priority.High, type.Documentation, type.Task

#292 Merge EyoWeiChin Documentation Update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/eyoweichin.md
Labels: type.Documentation

#293 Merge ChanJianHao-V21-User-NameChecks
  src/main/java/anichan/commands/WorkspaceCommand.java
  src/main/java/anichan/human/Human.java
  src/main/java/anichan/human/User.java
  src/main/java/anichan/logger/AniLogger.java
  src/test/java/anichan/human/UserTest.java
  src/test/java/anichan/parser/WorkspaceParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, severity.VeryLow, type.Bug

#294 Merge EyoWeiChin more input validation
  docs/UserGuide.md
  src/main/java/anichan/parser/BrowseParser.java
  src/main/java/anichan/parser/CommandParser.java
  src/main/java/anichan/parser/Parser.java
  src/main/java/anichan/parser/SearchParser.java
  src/test/java/anichan/parser/BrowseParserTest.java
  src/test/java/anichan/parser/SearchParserTest.java
Labels: severity.Low, type.Bug

#295 Update PPP (and for consistency), and updated UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AniChan-Input-Prompt.png
  docs/team/chanjianhao.md
  docs/team/eyoweichin.md
  docs/team/michaeldinata.md
  docs/team/n3wsoldier.md
  docs/team/ongdezhi.md
Labels: type.Documentation

#297 Merge OngXinBin-DeveloperGuide-v2.1
  docs/DeveloperGuide.md
  docs/team/n3wsoldier.md
Labels: type.Documentation

#299 Update PPP with minor formatting and phrasing fix
  docs/team/eyoweichin.md
  docs/team/n3wsoldier.md
Labels: type.Documentation

#301 Reorder Appendix D content
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#303 Update JavaDoc
  src/main/java/anichan/anime/AnimeData.java
  src/main/java/anichan/bookmark/Bookmark.java
  src/main/java/anichan/bookmark/Note.java
  src/main/java/anichan/commands/BookmarkCommand.java
Labels: priority.Low, type.Enhancement

#304 Merge - Add more comprehensive JavaDocs
  src/main/java/anichan/commands/BrowseCommand.java
  src/main/java/anichan/commands/SearchCommand.java
  src/main/java/anichan/parser/Parser.java
Labels: priority.Low, type.Enhancement

#302 Merge ChanJianHao-V21-Pre-Release-Updates
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/chanjianhao.md
  src/main/java/anichan/commands/WorkspaceCommand.java
  src/main/java/anichan/human/User.java
  src/main/java/anichan/parser/WorkspaceParser.java
Labels: priority.Medium, type.Documentation, type.Task

#307 Add more checks to EstimateParser and WatchlistStorage, and update PPP
  docs/team/chanjianhao.md
  docs/team/michaeldinata.md
  docs/team/n3wsoldier.md
  docs/team/ongdezhi.md
  src/main/java/anichan/parser/EstimateParser.java
  src/main/java/anichan/storage/Storage.java
  src/main/java/anichan/storage/WatchlistStorage.java
  src/test/data/StorageManagerTest/DirectoryWithInvalidFile/AllInvalidWorkspace/watchlist.txt
  src/test/java/anichan/parser/EstimateParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Documentation, type.Enhancement, type.Task

#308 Update JUnit test method name
  src/main/java/anichan/anime/AnimeStorage.java
  src/main/java/anichan/bookmark/Bookmark.java
  src/main/java/anichan/storage/BookmarkStorage.java
  src/test/java/anichan/commands/BookmarkCommandTest.java
  src/test/java/anichan/parser/BookmarkParserTest.java
  src/test/java/anichan/storage/StorageManagerTest.java
Labels: priority.Medium, type.Enhancement, type.Task

#305 Merge ChanJianHao-V21-Code-Improvement
  docs/team/chanjianhao.md
  src/main/java/anichan/Main.java
  src/main/java/anichan/human/User.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Task

#309 Merge EyoWeiChin Pre Release v2.1
  docs/team/eyoweichin.md
  src/main/java/anichan/commands/BrowseCommand.java
  src/main/java/anichan/parser/BrowseParser.java
  src/test/java/anichan/commands/BrowseCommandTest.java
Labels: priority.Medium, type.Documentation, type.Enhancement

#310 Merge ChanJianHao-V21-DG-FormatUpdates
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#312 Merge EyoWeiChin Anime JavaDocs
  src/main/java/anichan/anime/Anime.java
  src/main/java/anichan/commands/BookmarkCommand.java
  src/main/java/anichan/commands/BrowseCommand.java
  src/main/java/anichan/parser/BrowseParser.java
  src/main/java/anichan/parser/SearchParser.java
Labels: priority.Low, type.Bug, type.Documentation, type.Enhancement

#313 Merge input validation update
  src/main/java/anichan/commands/BookmarkCommand.java
  src/main/java/anichan/parser/BrowseParser.java
  src/test/java/anichan/anime/AnimeTest.java
  src/test/java/anichan/parser/BrowseParserTest.java
Labels: severity.VeryLow, type.Bug

#315 Update UG and DG diagrams spacing, and update PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ongdezhi.md
  src/main/java/anichan/storage/Storage.java
Labels: priority.Medium, type.Documentation

#317 Merge Update the image to reflect new changes
  docs/DeveloperGuide.md
  docs/images/User-Guide-Setting-Up.png
Labels: type.Documentation

#319 Merge ChanJianHao-V21-Javadocs-Minor-Fix
  docs/DeveloperGuide.md
  src/main/java/anichan/human/User.java
  src/main/java/anichan/logger/AniLogger.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Task

#318 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ongdezhi.md
Labels: priority.Low, type.Documentation

#321 Merge Update UG to change release link to V2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.VeryLow, type.Bug, type.Documentation
